#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Date    : 2017-05-09 11:46:11
# @Author  : lzg (wb-lzg228465@autonavi.com)
# @Link    : ${link}
# @Version : $Id$

import base64
a = base64.b64encode(b'yellow')
print(a)
print(base64.b64decode(a))


def safe_base64_decode(s):
    return base64.b64decode(s + b'=' * (4 - len(s) % 4))


def safe_base64_decode1(s):
    if len(s) % 4 == 0:
        return base64.b64decode(s)
    else:
        return safe_base64_decode(s + b'=')

if __name__ == '__main__':
    assert b'abcd' == safe_base64_decode(
        b'YWJjZA=='), safe_base64_decode('YWJjZA==')
    assert b'abcd' == safe_base64_decode(
        b'YWJjZA'), safe_base64_decode('YWJjZA')
    print('Pass')
